apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    haproxy.org/set-host: "carbon-tracker"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: server-nodeport
              servicePort: 8080
