version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: simon-norman
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - run:
          name: Install Docker client
          command: apk add docker-cli

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t simon1000/carbontracker:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push simon1000/carbontracker:$TAG