version: 2.1

jobs:
  build:
    docker:
      - image: google/cloud-sdk
        auth:
          username: simon1000
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project impact-284220
          gcloud --quiet config set compute/zone us-central1-c
          gcloud container clusters get-credentials carbon-tracker

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t simon1000/carbontracker:$TAG ./trackerproject
          echo $DOCKERHUB_PASSWORD | docker login -u simon1000 --password-stdin
          docker push simon1000/carbontracker:$TAG
          kubectl apply -f k8s/prod
          kubectl set image deployments/server-build server=simon1000/carbontracker:$TAG
          SERVER_BUILD_POD=$(kubectl get pod -l component=server-build -o jsonpath="{.items[0].metadata.name}")
          kubectl exec $SERVER_BUILD_POD python manage.py makemigrations
          kubectl exec $SERVER_BUILD_POD python manage.py migrate
          kubectl set image deployments/server-deployment server=simon1000/carbontracker:$TAG
